services:

  # mariadb:
  #   environment:
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #   container_name: mariadb
  #   build: requirements/mariadb
  #   image: mariadb:v_final
  #   volumes:
  #     - db_data:/var/lib/mysql
    # networks:
    #   - docker_network
  #   restart: always

  wordpress:
    environment:
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=aqwe123
    container_name: wordpress
    build: requirements/wordpress
    # image: wordpress:4.7.1-php7.0-fpm
    # depends_on: 
    #   - mariadb
    networks:
      - docker_network
    ports:
      - 9000
    volumes:
      - ./wordpress:/var/www/html/wordpress
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    # depends_on :
    #   - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    restart: always

networks:
  docker_network:

volumes:
  db_data: 
    driver: local
    driver_opts:
      type: none
      device: /home/atonkopi/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/atonkopi/data/wordpress
      o: bind