services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - docker_network
    restart: always
    volumes:
      - ./db:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    depends_on: 
      - mariadb
    networks:
      - docker_network
    expose:
      - "9000"
    volumes:
      - ./wordpress:/var/www/html/wordpress
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on :
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html/wordpress
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    restart: always

networks:
  docker_network: