services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    # image: mariadb:v_final
    networks:
      - docker_network
    env_file: .env
    restart: always
    volumes:
      - ./db:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    # image: wordpress:4.7.1-php7.0-fpm
    # depends_on: 
    #   - mariadb
    networks:
      - docker_network
    ports:
      - 9000
    volumes:
      - ./wordpress:/var/www/html/wordpress
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on :
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    restart: always

networks:
  docker_network:

volumes:
  db: 
    driver: local
    driver_opts:
      type: none
      device: /home/atonkopi/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/atonkopi/data/wordpress
      o: bind