services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - docker_network
    restart: always
    volumes:
      - ./db:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    environment:
      DB_HOST: mariadb
      DB_NAME: db
      DB_USER: atonkopi
      DB_PASSWORD: 123123
      WP_ADMIN_USER: atonkopi.root
      WP_ADMIN_PASSWORD: 123123
      WP_USER: atonkopi
      WP_USER_EMAIL: atonkopi@example.org
      WP_ADMIN_EMAIL: atonkopi.root@example.org
    depends_on: 
      - mariadb
    networks:
      - docker_network
    expose:
      - "9000"
    volumes:
      - ./wordpress:/var/www/html/wordpress
    restart: always

  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on :
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html/wordpress
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    restart: always

networks:
  docker_network: