CREATE DATABASE IF NOT EXISTS db;
CREATE USER IF NOT EXISTS 'atonkopi'@'%' IDENTIFIED BY '123123';
GRANT ALL PRIVILEGES ON db.* TO 'atonkopi'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '12312345';